### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by TomEasterbrook** [A-Lawrence/VatsimOSTicketAuth#3]
Hi all,

I have been attempting to use this plugin for a while now , using the demo server, to no avail. After following the steps regarding installation  I am not routed to the SSO login page during any stage of the login process. I wonder whether it would be possible for someone to help me resolve this?

Thanks

Tom

**Comment by damonhb** [comment]
I assume you've set up the site in https://cert.vatsim.net/sso/sso/sites/ ?

-Damon

**Comment by TomEasterbrook** [comment]
I have been trying to connect it to the demo server. Could this be what is
causing the problem?

Tom

On Sat, Jan 30, 2016 at 3:39 PM, damonhb <notifications@github.com> wrote:

> I assume you've set up the site in https://cert.vatsim.net/sso/sso/sites/
> ?
>
> -Damon
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/A-Lawrence/VatsimOSTicketAuth/issues/3#issuecomment-177212223>
> .
>



-- 
Regards,

Tom Easterbrook

This email and any attachments to it may be confidential and are intended
solely for the use of the individual to whom it is addressed. Any views or
opinions expressed are solely those of the author and do not necessarily
represent those of any other person or organisation

If you are not the intended recipient of this email, you must neither take
any action based upon its contents, nor copy or show it to anyone.

Please contact the sender if you believe you have received this email in
error.

**Comment by TomEasterbrook** [comment]
Hi all,

My live SSO application was approved this morning. However, despite updating my plug-in setting the login procedure remains unchanged. On closer inspection of the code I noticed that the plug-in script was unable to include several files. After rectifying this,there was still no change.

The errors below can be found when authenticate.php is accessed
`
Strict Standards: Static function AuthenticationBackend::getUser() should not be abstract in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.auth.php on line 342

Strict Standards: Static function AuthenticationBackend::signOut() should not be abstract in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.auth.php on line 345

Strict Standards: Declaration of TicketModel::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.user.php on line 36

Strict Standards: Declaration of User::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.user.php on line 161

Strict Standards: Declaration of Organization::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.organization.php on line 406

Strict Standards: Declaration of DynamicForm::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 246

Strict Standards: Declaration of DynamicFormField::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 654

Strict Standards: Declaration of DynamicFormField::save() should be compatible with VerySimpleModel::save($refetch = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 654

Strict Standards: Declaration of DynamicFormEntry::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 1049

Strict Standards: Declaration of DynamicFormEntryAnswer::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 1166

Strict Standards: Declaration of SelectionField::getWidget() should be compatible with FormField::getWidget($widgetClass = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 1381

Strict Standards: Declaration of TypeaheadSelectionWidget::render() should be compatible with ChoicesWidget::render($mode = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.dynamic_forms.php on line 1457

Strict Standards: Declaration of DynamicList::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.list.php on line 132

Strict Standards: Declaration of DynamicListItem::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.list.php on line 456

Strict Standards: Declaration of TicketStatus::delete() should be compatible with VerySimpleModel::delete($pk = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.list.php on line 779

Strict Standards: Declaration of TicketStatus::create() should be compatible with VerySimpleModel::create($ht = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.list.php on line 779

Notice: Use of undefined constant TICKET_STATUS_TABLE - assumed 'TICKET_STATUS_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 139

Notice: Use of undefined constant TICKET_TABLE - assumed 'TICKET_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 147

Notice: Use of undefined constant ORGANIZATION_TABLE - assumed 'ORGANIZATION_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 139

Notice: Use of undefined constant USER_TABLE - assumed 'USER_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 147

Notice: Use of undefined constant USER_EMAIL_TABLE - assumed 'USER_EMAIL_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 147

Notice: Use of undefined constant USER_ACCOUNT_TABLE - assumed 'USER_ACCOUNT_TABLE' in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.orm.php on line 147

Strict Standards: Declaration of Message::create() should be compatible with ThreadEntry::create($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1261

Strict Standards: Declaration of Message::add() should be compatible with ThreadEntry::add($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1261

Strict Standards: Declaration of Response::create() should be compatible with ThreadEntry::create($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1313

Strict Standards: Declaration of Response::add() should be compatible with ThreadEntry::add($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1313

Strict Standards: Declaration of Note::create() should be compatible with ThreadEntry::create($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1352

Strict Standards: Declaration of Note::add() should be compatible with ThreadEntry::add($vars) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.thread.php on line 1352

Strict Standards: Declaration of RandomSequence::save() should be compatible with VerySimpleModel::save($refetch = false) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.sequence.php on line 234

Strict Standards: Declaration of VatsimAuthConfig::pre_save() should be compatible with PluginConfig::pre_save($config, &$errors) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/config.php on line 103

Notice: Constant INCLUDE_DIR already defined in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/config.php on line 2

Notice: Constant PEAR_DIR already defined in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/config.php on line 3`

The following errors can be found on config.php.
`Strict Standards: Declaration of VatsimAuthConfig::pre_save() should be compatible with PluginConfig::pre_save($config, &$errors) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/config.php on line 8`

Any assistance would be greatly appreciated.

Tom

**Comment by A-Lawrence** [comment]
What version of PHP are you running?

**Comment by TomEasterbrook** [comment]
5.5

**Comment by TomEasterbrook** [comment]
@A-Lawrence Can you confitm what version of osticket you used to create this plugin

**Comment by A-Lawrence** [comment]
1.8 originally, now running the latest 1.9 release.

**Comment by A-Lawrence** [comment]
All of those errors you've got are because you've got E_STRICT errors enabled.  For now, I'd suggest disabling them as not a single error there is caused by this plugin.

**Comment by TomEasterbrook** [comment]
@A-Lawrence  Even if I disable errors, I am not routed to sso to sign in when I press log in.  I wonder wheither you could spare some time on Skype or TS to discuss this further.

Thanks your help thus far,

Ton

**Comment by TomEasterbrook** [comment]
@A-Lawrence , it appears that error reporting was not disabled as I previously thought. However, I now receive the following error from within my web browser and no login form or any part of the helpdesk appears.
![error](https://cloud.githubusercontent.com/assets/5488110/12867937/0db06a30-ccf3-11e5-9f5b-87547a3d0b7f.PNG)

**Comment by A-Lawrence** [comment]
@TomEasterbrook I can't do much with that screenshot unfortunately.  What entry do you have in your apache error log?

**Comment by TomEasterbrook** [comment]
@A-Lawrence These certainly look a bit more useful!

[13-Feb-2016 04:25:22 America/New_York] PHP Warning:  Missing argument 1 for Plugin::Plugin(), called in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/authenticate.php on line 102 and defined in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.plugin.php on line 360
[13-Feb-2016 04:25:22 America/New_York] PHP Warning:  include(/plugin.php): failed to open stream: No such file or directory in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.plugin.php on line 280
[13-Feb-2016 04:25:22 America/New_York] PHP Warning:  include(): Failed opening '/plugin.php' for inclusion (include_path='./:/home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/:/home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/pear/') in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.plugin.php on line 280
[13-Feb-2016 04:25:22 America/New_York] PHP Warning:  array_merge(): Argument #2 is not an array in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/class.plugin.php on line 280
[13-Feb-2016 04:25:22 America/New_York] PHP Parse error:  syntax error, unexpected 'class' (T_CLASS) in /home/tomeaste/public_html/vatsim-wa.com/Helpdesk/include/plugins/auth-vatsim/SSO.class.php on line 8

**Comment by A-Lawrence** [comment]
That's more like it! Something we can work with.

Can you send me an email with your Skype details and maybe I can remote access and take a look for you?

**Comment by TomEasterbrook** [comment]
You should be able add me using my email tomeasterbrook98@gmail.com I can chat anytime between 3 and 6 today would if you are free, please 

Thanks,
Tom

**Comment by A-Lawrence** [comment]
As discussed on Skype - the root issue was that your IP wasn't registered with SSO.  Fresh copy of the plugin was installed to overwrite local changes that were causing errors.

Other server errors were fairly superfluous and stemming from OSTicket issues rather than extension ones.
